name: Starter Workflow Demo
on: 
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: demo workflow job step 1
      run: echo Demo tests setup
 
  Unit-tests:
    runs-on: ubuntu-latest
    needs: setup
    
    steps: 
    - uses: actions/checkout@v3
    - name: demo workflow job Step 2
      run: echo This is a fail step
    - name: Install Mocha
      run: npm install mocha && echo successfully Installed !!
